# Site wide configuration

title: André Yuhai
locale: en_US
description: A computer engineering student </br> who loves programming languages and the ones we speak
logo: logo.jpg
search: true
words_per_minute: 200
url: http://blog.andreyuhai.com
#url: http://localhost:4000

# Jekyll configuration

permalink:   /:categories/:title/
markdown:    kramdown
sass:
  sass_dir: _sass
  style: compressed
gems:
  - jekyll-sitemap

kramdown:
  auto_ids: true
  footnote_nr: 1
  entity_output: as_char
  toc_levels: 1..4
  use_coderay: false
  syntax_highlighter: rouge

include: [".htaccess"]
exclude: ["lib", "config.rb", "Capfile", "config", "log", "Rakefile", "Rakefile.rb", "tmp", "less", "*.sublime-project", "*.sublime-workspace", "test", "spec", "Gruntfile.js", "package.json", "node_modules", "Gemfile", "Gemfile.lock", "LICENSE", "README.md", "vendor"]


# Site owner
owner:
  name: André Yuhai
  avatar: avatar4.jpg
  email: yuhai.ndre@gmail.com
  disqus-shortname: thatwhichinspiresawe
  twitter: andreyuhai
  facebook: #username
  github: andreyuhai
  stackexchange: https://stackoverflow.com/users/4796762/andré-yuhai
  linkedin: indrekots
  instagram: andreyuhai
  flickr: #username
  tumblr: #username
  google:
    plus: #username
    analytics: 
    verify:
    ad-client:
    ad-slot:
  bing-verify:
